version: '3.7'

services:
  postgres-service:
    container_name: postgres-service
    image: postgres:16.1-bullseye
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cart
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - app

  cart-service:
    container_name: cart-service
    image: hrmtn/cart:0.0.2-SNAPSHOT
    ports:
      - '8080:8080'
    environment:
      - 'spring.r2dbc.url=r2dbc:postgresql://postgres-service:5432/cart'
      - 'spring.r2dbc.username=root'
      - 'spring.r2dbc.password=root'
      - 'spring.flyway.url=jdbc:postgresql://postgres-service:5432/cart'
      - 'spring.flyway.user=root'
      - 'spring.flyway.password=root'
      - 'spring.kafka.bootstrap-servers=kafka:9092'
    depends_on:
      - postgres-service
    networks:
      - app

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - app

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "validated-orders:1:1"
    depends_on:
      - zookeeper
    networks:
      - app

networks:
    app:
        driver: bridge