version: '3.7'

services:
  postgres-service:
    container_name: postgres-service
    image: postgres:16.1-bullseye
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cart
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
